### ISSUE TITLE
team

### ISSUE THREAD

**Issue by eguaman1990** [PlataformaGroup/PlataformaGroup.API#1]
shalalalala

**Comment by eguaman1990** [comment]
comment lalala

**Comment by francodeline** [comment]
khé

*Franco Ljubetic.*
Ingeniería en informática.
Desarrollo de sitios web.
Celular: 9 657 88 493

2016-12-16 15:47 GMT-03:00 Edwin Andres Guaman Criollo <
notifications@github.com>:

**Comment by eguaman1990** [comment]
estaba probando

**Comment by francodeline** [comment]
😐

*Franco Ljubetic.*
Ingeniería en informática.
Desarrollo de sitios web.
Celular: 9 657 88 493

2016-12-16 15:51 GMT-03:00 Edwin Andres Guaman Criollo <
notifications@github.com>:
